config/routes.rb
RubyBegin::Application.routes.draw do
  root 'home#index'
  
  get '/feedback', to: 'feedback#index'
  post '/feedback', to: 'feedback#add'
  get '/feedback/congratulations'
  get '/feedback/list'
  post '/feedback/remove'

  get '/login', to: 'auth#index'
  post '/login', to: 'auth#login'
  get '/logout', to: 'auth#logout'

  get '/get_self', to: 'self_json#get_self'
  post '/update_self', to: 'self_json#update_self'

  get '/admin', to: 'admin#index'
  get '/admin/feedback_list'

end

app/models/feedback.rb
class Feedback
  include Mongoid::Document
  validates :name,
            :text,
            :presence => true

  field :name, type: String
  field :text, type: String
end

app/models/my_self.rb
class MySelf
  include Mongoid::Document
  validates :name,
            :city,
            :date_birth,
            :email,
            :phone,
            :vk,
            :presence => true

  validate :array_not_nil

  field :name, type: String
  field :city, type: String
  field :date_birth, type: DateTime
  field :technologies, type: Array, default: []
  field :interests, type: Array, default: []
  field :email, type: String
  field :phone, type: String
  field :vk, type: String

  embeds_many :works
  embeds_many :studies

  private

  def array_not_nil
    errors.add(:technologies, 'nil') if technologies.nil?
    errors.add(:interests, 'nil') if interests.nil?
    errors.add(:works, 'nil') if works.nil?
    errors.add(:studies, 'nil') if studies.nil?
  end
end

app/models/study.rb
class Study
  include Mongoid::Document
  validates :from,
            :name,
            :desc,
            :presence => true

  field :from, type: DateTime
  field :to, type: DateTime
  field :name, type: String
  field :desc, type: String

  embedded_in :my_self
end

app/models/user.rb
class User
  include Mongoid::Document
  validates :name, presence: true
  validates :pass, presence: true

  field :name, type: String
  field :pass, type: String
end

app/models/work.rb
class Work
  include Mongoid::Document
  validates :from,
            :name,
            :profession,
            :occupation,
            :presence => true

  field :from, type: DateTime
  field :to, type: DateTime
  field :name, type: String
  field :profession, type: String
  field :occupation, type: String

  embedded_in :my_self
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :reject_non_auth_request

  def index

  end

  def feedback_list
    
  end

end

app/controllers/application_controller.rb
require "#{Rails.root}/lib/authenticate/user_provider.rb"

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :init_vars

  protected
  def user_provider
    @user_provider
  end

  def reject_non_auth_request
    unless user_provider.user_logged_in?
      Rails.logger.warn("Some person try to access to #{controller_name}/#{action_name} before authenticating")
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  private
  def init_vars
    @user_provider = UserProvider.new(session)
  end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  layout 'front'

  def index
    @title = '::Sign in'
  end

  def login

    user = User.new(params.permit(:name, :pass))

    if user_provider.login(user)
      redirect_to controller: 'home', action: 'index'
    else
      flash['auth_error'] = 'Неа!'
      redirect_to action: 'index'
    end

  end

  def logout
    user_provider.logout
    redirect_to controller: 'home', action: 'index'
  end

end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  layout 'front'
  before_filter :reject_non_auth_request, only: [:remove, :list]

  def index
    @title = '::Feedback'
  end

  def congratulations
    @title = '::Congratulations'
  end

  def add
    feedback = Feedback.new(params.permit(:name, :text))

    if feedback.valid?
      feedback.save!
      FeedbackMailer.entry_added(feedback).deliver
    end

    redirect_to action: 'congratulations'
  end

  def remove
    id = params[:id]
    feedback = Feedback.find(id)

    if feedback.nil?
      render json: "can't find"
    else
      feedback.delete
      render json: "ok"
    end
  end


  def list
    all_feedback = Feedback.all.to_a

    render json: all_feedback
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'front'

  def index
    @title = "::Main Page"
    @self = MySelf.first
    @years_old = (DateTime.now.to_i - @self.date_birth.to_i) / 60 / 60 / 24 / 365
  end

end

app/controllers/self_json_controller.rb
class SelfJsonController < ApplicationController
  before_filter :reject_non_auth_request, except: :get_self

  def get_self
    my_self = MySelf.first
    render json: my_self
  end

  def update_self
    result = false

    begin
      my_self = MySelf.new(params.permit!.except(:controller, :action))
    rescue
      Rails.logger.error("Can't convert params to MySelf model in #{controller_name}/#{action_name}")
      my_self = MySelf.new
    end

    if my_self.valid?
      MySelf.destroy_all
      result = my_self.save!
    end

    render json: result
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_provider
    @user_provider
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/feedback_list.html.erb
<script src="/js/feedback_controller.js"></script>

<div style="text-align: center; position: absolute; width: 100%;">
  <%= link_to 'Резюме', admin_path %>
</div>

<div class="container jumbotron" ng-controller="feedbackCtrl">

  <h1>Отзывы <small>({{feedbackList.length}} отзывов)</small></h1>

  <div ng-repeat="feedback in feedbackList track by $index">
    <h4>
      <span class="btn btn-danger btn-xs" ng-click="delEntry($index)">&times;</span>
      {{feedback.name}}
    </h4>
    <p>
      {{feedback.text}}
    </p>
  </div>

</div>

app/views/admin/index.html.erb
<script src="/js/admin_controller.js"></script>

<div style="text-align: center; position: absolute; width: 100%;">
  <%= link_to 'Отзывы', admin_feedback_list_path %>
</div>

<div class="container jumbotron" ng-controller="adminCtrl">

  <h1>Резюме</h1>

  <div class="form-horizontal">

    <div class="form-group">
      <label for="name" class="col-sm-2 control-label">Имя:</label>

      <div class="col-sm-3">
        <input id="name" type="text" ng-model="mySelf.name" class="form-control">
      </div>

    </div>

    <div class="form-group">
      <label for="date" class="col-sm-2 control-label">День рождения:</label>

      <div class="col-sm-3">
        <input id="date" type="date" ng-model="mySelf.date_birth" class="form-control">
      </div>
    </div>

    <div class="form-group">
      <label for="city" class="col-sm-2 control-label">Город:</label>

      <div class="col-sm-3">
        <input id="city" type="text" ng-model="mySelf.city" class="form-control">
      </div>
    </div>

    <div class="form-group">
      <label for="phone" class="col-sm-2 control-label">Город:</label>

      <div class="col-sm-3">
        <input id="phone" type="text" ng-model="mySelf.phone" class="form-control">
      </div>
    </div>

    <div class="form-group">
      <label for="email" class="col-sm-2 control-label">Email:</label>

      <div class="col-sm-3">
        <input id="email" type="text" ng-model="mySelf.email" class="form-control">
      </div>
    </div>

    <div class="form-group">
      <label for="vk" class="col-sm-2 control-label">VK:</label>

      <div class="col-sm-3">
        <input id="vk" type="text" ng-model="mySelf.vk" class="form-control">
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Технологии:</label>

      <div class="col-sm-3">
        <div ng-repeat="tech in mySelf.technologies track by $index" class="input-group">
          <input type="text" ng-model="mySelf.technologies[$index]" class="form-control">
          <span class="input-group-addon btn" ng-click="delTech($index)">Delete</span>
        </div>
      </div>
      <button class="btn btn-primary" ng-click="newTech()">Add</button>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Интересы:</label>

      <div class="col-sm-3">
        <div ng-repeat="interest in mySelf.interests track by $index" class="input-group">
          <input type="text" ng-model="mySelf.interests[$index]" class="form-control">
          <span class="input-group-addon btn" ng-click="delInterest($index)">Delete</span>
        </div>
      </div>
      <button class="btn btn-primary" ng-click="newInterest()">Add</button>
    </div>


    <div class="form-group">
      <label class="col-sm-2 control-label">Учеба:</label>

      <div class="col-sm-4">
        <div ng-repeat="study in mySelf.studies track by $index">
          <div class="form-group row">
            <button class="btn btn-danger pull-right" style="margin-right: 15px;" ng-click="delStudy($index)">Delete</button>
          </div>
          <div class="form-group">
            <label for="study-from" class="col-sm-3 control-label">Начало:</label>

            <div class="col-sm-9">
              <input id="study-from" type="date" ng-model="study.from" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label for="study-to" class="col-sm-3 control-label">Конец:</label>

            <div class="col-sm-9">
              <input id="study-to" type="date" ng-model="study.to" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label for="study-name" class="col-sm-3 control-label">Имя:</label>

            <div class="col-sm-9">
              <input id="study-name" type="text" ng-model="study.name" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label for="study-desc" class="col-sm-3 control-label">Описание:</label>

            <div class="col-sm-9">
              <textarea rows="6" id="study-desc" ng-model="study.desc" class="form-control">
              </textarea>
            </div>
          </div>
        </div>
      </div>
      <button class="btn btn-primary" ng-click="newStudy()">Add</button>
    </div>


    <div class="form-group">
      <label class="col-sm-2 control-label">Работа:</label>

      <div class="col-sm-4">
        <div ng-repeat="work in mySelf.works track by $index">
          <div class="form-group row">
            <button class="btn btn-danger pull-right" style="margin-right: 15px;" ng-click="delWork($index)">Delete</button>
          </div>
          <div class="form-group">
            <label for="work-from" class="col-sm-3 control-label">Начало:</label>

            <div class="col-sm-9">
              <input id="work-from" type="date" ng-model="work.from" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label for="work-to" class="col-sm-3 control-label">Конец:</label>

            <div class="col-sm-9">
              <input id="work-to" type="date" ng-model="work.to" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label for="work-name" class="col-sm-3 control-label">Имя:</label>

            <div class="col-sm-9">
              <input id="work-name" type="text" ng-model="work.name" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label for="work-profession" class="col-sm-3 control-label">Должность:</label>

            <div class="col-sm-9">
              <input id="work-profession" type="text" ng-model="work.profession" class="form-control">
            </div>
          </div>
          <div class="form-group">
            <label for="work-occupation" class="col-sm-3 control-label">Обязаности:</label>

            <div class="col-sm-9">
              <input id="work-occupation" type="text" ng-model="work.occupation" class="form-control">
            </div>
          </div>
        </div>
      </div>
      <button class="btn btn-primary" ng-click="newWork()">Add</button>
    </div>

    <button class="btn btn-warning btn-lg" ng-click="update()" style="position: fixed; top: 0; left: 0;">Update</button>
  </div>


</div>

app/views/feedback/congratulations.html.erb
<h1>Congratulations</h1>
<p>
Спасибо, я прочту ваще сообщение.
</p>
<p>
<a href="/">На главную.</a>
</p>

app/views/feedback/index.html.erb
<h1>Feedback</h1>

<%= form_tag method: 'post' do %>
  <div class="form-row">
    <strong><label for="name">Ваше имя:</label></strong>
  </div>
  <div class="form-row">
    <input id="name" type="text" name="name" class="width100"/>
  </div>
  <div class="form-row">
    <strong><label for="text">Сообщение:</label></strong>
  </div>
  <div class="form-row">
    <textarea name="text" id="text" cols="30" rows="10" class="width100"></textarea>
  </div>
  <div class="form-row">
    <input type="submit" value="Отпрвить" class="btn" />
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Who am I</h1>
<p>
  Меня зовут Виктор. Сейчас мне <%= @years_old %>. <br>
  Живу в городе Фурманов, работаю программистом в городе Иваново. <br>
  Иногда рисую всякую хрень. =)
</p>

<h1>Technologies</h1>
<p>
  Технологиями, которыми я владею на приемлемом уровне, использую их в каждодневной разработке:
</p>
<ul>
  <% @self.technologies.each do |tech| %>
    <li>
      <%= tech %>
    </li>
  <% end %>
</ul>

<h1>Interests</h1>
<p>
  То что мне интеренсно, хотелось бы воспользоваться или изучить подробнее:
</p>
<ul>
  <% @self.interests.each do |interest| %>
    <li>
      <%= interest %>
    </li>
  <% end %>
</ul>

<h1>Latest jobs</h1>
<p>
  Последние места, где я работал:
</p>
<ul>
  <% @self.works.reverse.each do |work| %>
    <li>
      Компания - "<%= work.name %>", занятие - <%= work.occupation %>
    </li>
  <% end %>
</ul>

<h1>Contact</h1>
<table>
  <tr>
    <td>
      Почта:
    </td>
    <td>
      <a href="mailto:<%= @self.email %>"><%= @self.email %></a>, или <%= link_to 'Фидбэк', feedback_path %> на сайте
    </td>
  </tr>
  <tr>
    <td>
      VK:
    </td>
    <td>
      <a href="<%= @self.vk %>" target="_blank"><%= @self.vk %></a>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="mainApp">
<head>
  <title>hobbit_admin</title>
  <meta name="description" content="Голов Виктор. Моя домашнаяя страница" />
  <meta name="keywords" content="Голов, Виктор, резюме, домашнаяя страница" />

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>


  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js"></script>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>

  <script type="text/javascript" charset="utf-8">
      var mainApp = angular.module('mainApp', []);
  </script>

  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
	
  <%= yield %>

</body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Голов Виктор<%= @title %></title>
  <meta name="description" content="Голов Виктор. Личная страница." />
  <meta name="keywords" content="голов, виктор, голов виктор, резюме, личная страница, golov, victor, golov victor" />
  <meta name="google-site-verification" content="PvcqNtT5d3KcQVZ2odsxptK4fF5hGlILiixeWFL1_Cs" />
  <link rel="icon" type="image/png" href="favicon.png" />

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class="inner">
      <h1>
        Hi there! This is my website =)
      </h1>
      <h2>
        Golov Victor
      </h2>
      <a href="/"></a>
    </div>
  </header>

  <div id="main">
    <div class="inner clearfix">

      <section>
        <%= yield %>
      </section>

      <aside>
        <%= render "shared/aside" %>
      </aside>

    </div>
  </div>

  <!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter25170968 = new Ya.Metrika({id:25170968, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/25170968" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->

</body>
</html>

app/views/shared/_aside.html.erb
<p>
  <%= link_to "Связаться", feedback_path %> со мной
</p>

<p>
  Powered by: <br>

  <a href="http://rubyonrails.org/" target="_blank" class="powered ruby">
    <span>Ruby on Rails</span>
  </a>
  <a href="http://www.mongodb.com/" target="_blank" class="powered mongo">
    <span>MongoDB</span>
  </a>
</p>

<p>
  <small>
    This website was created by me,
    using the Architect theme by <a href="https://twitter.com/jasonlong" target="_blank">Jason Long</a>.
  </small>
</p>

<% if user_provider.user_logged_in? %>
  <h1>
    Hello <%= user_provider.user_name %>
    <%= link_to 'root', admin_path %>
  </h1>
<% end %>